#!/bin/bash

# Ubuntu
printf "\nStarting the Ubuntu test...\n" &&

docker run -v $(pwd)/test:/test -v $(pwd):/opt/bin \
    -w /test --name=dotman_ubuntu ubuntu:latest \
    /bin/bash -c /test/test &&

# CentOS
printf "\nStarting the CentOS test...\n" &&

docker run -v $(pwd)/test:/test -v $(pwd):/opt/bin \
    -w /test --name=dotman_centos centos:latest \
    /bin/bash -c /test/test &&

# SUSE
printf "\nStarting the SUSE test...\n" &&

docker run -v $(pwd)/test:/test -v $(pwd):/opt/bin \
    -w /test --name=dotman_suse opensuse:latest \
    /bin/bash -c /test/test &&

printf "\n\tAll tests passed!\n\n";
printf "Removing containers...\n\n";

SUS=$(docker stop -t 0 dotman_suse);
SUS=$(docker rm dotman_suse);
UBU=$(docker stop -t 0 dotman_ubuntu);
UBU=$(docker rm dotman_ubuntu);
COS=$(docker stop -t 0 dotman_centos);
COS=$(docker rm dotman_centos);
