#!/bin/bash

# Define pass/fail functions
pass() {
  printf "\n\tPASS\n\n";
}

fail() {
  printf "\n\tFAIL\n\n";
  cleanup;
  exit 1;
}

cleanup() {
  rm file;
  echo "content" > dir/.file;
  rm .dotman;
}

touch .dotman;

printf "* Should add and import a file\n\n";

/opt/bin/dotman add dir/.file file;
FILE=$(cat file);
if [ ! "$FILE" ]; then
  fail;
else
  pass;
fi

printf "* Should import changes\n\n";

echo "edit" > dir/.file;
/opt/bin/dotman import file;
RESULT=$(cat file | grep -w edit);
if [ ! "$RESULT" ]; then
  fail;
else
  pass;
fi

printf "* Should export changes\n\n";

echo "content" > dir/.file;
/opt/bin/dotman export file;
RESULT=$(cat dir/.file | grep -w edit);
if [ ! "$RESULT" ]; then
  fail;
else
  pass;
fi

printf "* Should remove an entry\n\n";

/opt/bin/dotman rm file;
RESULT=$(cat .dotman | grep -w file);
if [ "$RESULT" ]; then
  fail;
else
  pass;
fi

# All passing
cleanup;
